<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { Plus, RefreshCw, Save, ShieldCheck } from "@lucide/vue";
import { api } from "../api";
import { displayDate, errorMessage, useUI } from "../ui";
import AppModal from "../components/AppModal.vue";
import EmptyState from "../components/EmptyState.vue";
import PageHeader from "../components/PageHeader.vue";

interface Site { id: string; domain: string; aliases: string[] }
interface Certificate { id: string; siteId: string; domains: string[]; email: string; challenge: string; expiresAt: string; lastError?: string; autoRenew: boolean; renewalDue: boolean }
const { notify } = useUI(); const loading = ref(false); const sites = ref<Site[]>([]); const certificates = ref<Certificate[]>([]); const modal = ref(false);
const dns = reactive({ defaultEmail: "", cloudflareToken: "", cloudflareConfigured: false, clearCloudflare: false });
const form = reactive({ siteId: "", domains: "", email: "", challenge: "http", provider: "cloudflare", autoRenew: true });
const selectedSite = computed(() => sites.value.find(site => site.id === form.siteId));
async function load() { loading.value = true; try { const [certData, siteData, dnsData] = await Promise.all([api<{ certificates: Certificate[] }>("/api/admin/certificates"), api<{ sites: Site[] }>("/api/admin/sites"), api<{ defaultEmail: string; cloudflareConfigured: boolean }>("/api/admin/dns-settings")]); certificates.value = certData.certificates; sites.value = siteData.sites; Object.assign(dns, dnsData, { cloudflareToken: "", clearCloudflare: false }); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function saveDNS() { loading.value = true; try { const value = await api<{ defaultEmail: string; cloudflareConfigured: boolean }>("/api/admin/dns-settings", { method: "PUT", body: { defaultEmail: dns.defaultEmail, cloudflareToken: dns.cloudflareToken, clearCloudflare: dns.clearCloudflare } }); Object.assign(dns, value, { cloudflareToken: "", clearCloudflare: false }); notify("DNS 设置已保存"); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
function open() { const site = sites.value[0]; Object.assign(form, { siteId: site?.id || "", domains: site ? [site.domain, ...site.aliases].join(", ") : "", email: dns.defaultEmail, challenge: "http", provider: "cloudflare", autoRenew: true }); modal.value = true; }
function siteChanged() { const site = selectedSite.value; if (site) form.domains = [site.domain, ...site.aliases].join(", "); }
async function issue() { loading.value = true; try { await api("/api/admin/certificates", { method: "POST", body: { siteId: form.siteId, domains: form.domains.split(",").map(v => v.trim()).filter(Boolean), email: form.email, challenge: form.challenge === "dns" ? `dns-${form.provider}` : "http", autoRenew: form.autoRenew } }); notify("证书申请完成"); modal.value = false; await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function renew(item: Certificate) { loading.value = true; try { await api(`/api/admin/certificates/${encodeURIComponent(item.id)}/renew`, { method: "POST" }); notify("证书续期完成"); await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
onMounted(load);
</script>
<template>
  <PageHeader title="证书管理" subtitle="Let's Encrypt 申请、DNS 验证与自动续期" kicker="CERTIFICATES"><button class="button primary" :disabled="!sites.length" @click="open"><Plus :size="16" />申请证书</button></PageHeader>
  <form class="settings-panel" @submit.prevent="saveDNS"><div class="section-title"><div><h2>DNS 设置</h2><span>凭据加密保存在本机数据库</span></div><button class="button primary" :disabled="loading"><Save :size="16" />保存设置</button></div><div class="form-grid"><label class="field">默认证书邮箱<input v-model="dns.defaultEmail" type="email" placeholder="admin@example.com"></label><label class="field">Cloudflare API Token<input v-model="dns.cloudflareToken" type="password" autocomplete="new-password" :placeholder="dns.cloudflareConfigured ? '已配置，留空保持不变' : '输入 API Token'"></label><label v-if="dns.cloudflareConfigured" class="check-field full"><input v-model="dns.clearCloudflare" type="checkbox">清除已保存的 Cloudflare 凭据</label></div></form>
  <section class="section-block"><div class="section-title"><div><h2>托管证书</h2><span>{{ certificates.length }} 张证书</span></div></div><div class="data-surface"><div class="table-scroll"><table class="data-table"><thead><tr><th>网站</th><th>域名</th><th>验证</th><th>到期时间</th><th>自动续期</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="item in certificates" :key="item.id"><td>{{ sites.find(site => site.id === item.siteId)?.domain || item.siteId }}</td><td class="truncate-cell" :title="item.domains.join(', ')">{{ item.domains.join(', ') }}</td><td>{{ item.challenge === 'dns-cloudflare' ? 'DNS / Cloudflare' : 'HTTP' }}</td><td>{{ displayDate(item.expiresAt, true) }}</td><td>{{ item.autoRenew ? '开启' : '关闭' }}</td><td><span class="status-pill" :class="{ running: !item.lastError && !item.renewalDue, stopped: item.renewalDue || !!item.lastError }" :title="item.lastError">{{ item.lastError ? '续期失败' : item.renewalDue ? '待续期' : '有效' }}</span></td><td><button class="icon-button" title="立即续期" :disabled="loading" @click="renew(item)"><RefreshCw :size="16" /></button></td></tr></tbody></table></div><EmptyState v-if="!loading && !certificates.length" message="暂无托管证书" /></div></section>
  <AppModal v-if="modal" title="申请证书" :busy="loading" submit-label="申请证书" @close="modal = false" @submit="issue"><div class="form-grid one-column"><label class="field">网站<select v-model="form.siteId" required @change="siteChanged"><option v-for="site in sites" :key="site.id" :value="site.id">{{ site.domain }}</option></select></label><label class="field">证书域名<input v-model="form.domains" required placeholder="example.com, www.example.com"></label><label class="field">联系邮箱<input v-model="form.email" type="email"></label><fieldset class="option-field"><legend>验证方式</legend><label><input v-model="form.challenge" type="radio" value="http">HTTP</label><label><input v-model="form.challenge" type="radio" value="dns">DNS</label></fieldset><label v-if="form.challenge === 'dns'" class="field">DNS 服务商<select v-model="form.provider"><option value="cloudflare">Cloudflare {{ dns.cloudflareConfigured ? '（已配置）' : '（未配置）' }}</option></select></label><label class="check-field"><input v-model="form.autoRenew" type="checkbox">自动续期</label></div><template #actions><button class="button quiet" type="button" @click="modal = false">取消</button><button class="button primary" type="submit" :disabled="loading"><ShieldCheck :size="16" />申请</button></template></AppModal>
</template>
