<script setup lang="ts">
import { onMounted, reactive, ref } from "vue"; import { Database, Plus, Trash2, UserPlus } from "@lucide/vue"; import { api } from "../api"; import { errorMessage, formatBytes, useUI } from "../ui"; import AppModal from "../components/AppModal.vue"; import EmptyState from "../components/EmptyState.vue"; import PageHeader from "../components/PageHeader.vue";
interface DB { name: string; size: number; tables: number } interface User { user: string; host: string; plugin: string }
const { notify, confirm } = useUI(); const databases = ref<DB[]>([]); const users = ref<User[]>([]); const loading = ref(false); const dbModal = ref(false); const userModal = ref(false); const dbForm = reactive({ name: "", charset: "utf8mb4" }); const userForm = reactive({ user: "", host: "localhost", password: "", database: "", privileges: ["ALL"] });
async function load() { loading.value = true; try { const [d, u] = await Promise.all([api<{ databases: DB[] }>("/api/admin/databases"), api<{ users: User[] }>("/api/admin/database-users")]); databases.value = d.databases; users.value = u.users; } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
function newDB() { Object.assign(dbForm, { name: "", charset: "utf8mb4" }); dbModal.value = true; } function newUser() { if (!databases.value.length) return notify("请先创建数据库", "error"); Object.assign(userForm, { user: "", host: "localhost", password: "", database: databases.value[0].name, privileges: ["ALL"] }); userModal.value = true; }
async function createDB() { loading.value = true; try { await api("/api/admin/databases", { method: "POST", body: dbForm }); notify("数据库已创建"); dbModal.value = false; await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function createUser() { loading.value = true; try { await api("/api/admin/database-users", { method: "POST", body: userForm }); notify("数据库用户已创建"); userModal.value = false; await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function removeDB(item: DB) { if (!await confirm(`删除数据库 ${item.name}`, "数据库和其中全部数据将被永久删除。", "永久删除", true)) return; try { await api(`/api/admin/databases/${encodeURIComponent(item.name)}`, { method: "DELETE" }); notify("数据库已删除"); await load(); } catch (e) { notify(errorMessage(e), "error"); } }
async function removeUser(item: User) { if (!await confirm(`删除用户 ${item.user}@${item.host}`, "该用户的数据库不会被删除。", "删除", true)) return; try { await api(`/api/admin/database-users/${encodeURIComponent(item.user)}?host=${encodeURIComponent(item.host)}`, { method: "DELETE" }); notify("数据库用户已删除"); await load(); } catch (e) { notify(errorMessage(e), "error"); } }
onMounted(load);
</script>
<template><PageHeader title="数据库" subtitle="MariaDB/MySQL 数据库与授权用户" kicker="DATABASES"><button class="button" @click="newUser"><UserPlus :size="16" />添加用户</button><button class="button primary" @click="newDB"><Plus :size="16" />创建数据库</button></PageHeader><div class="split-sections"><section><div class="section-title"><div><h2>数据库</h2><span>{{ databases.length }} 个</span></div></div><div class="data-surface"><div class="table-scroll"><table class="data-table"><thead><tr><th>名称</th><th>表</th><th>大小</th><th></th></tr></thead><tbody><tr v-for="item in databases" :key="item.name"><td><strong>{{ item.name }}</strong></td><td>{{ item.tables }}</td><td>{{ formatBytes(item.size) }}</td><td><button class="icon-button danger" title="删除数据库" @click="removeDB(item)"><Trash2 :size="16" /></button></td></tr></tbody></table></div><EmptyState v-if="!loading && !databases.length" message="暂无业务数据库" /></div></section><section><div class="section-title"><div><h2>数据库用户</h2><span>{{ users.length }} 个</span></div></div><div class="data-surface"><div class="table-scroll"><table class="data-table"><thead><tr><th>用户</th><th>允许主机</th><th>认证</th><th></th></tr></thead><tbody><tr v-for="item in users" :key="`${item.user}@${item.host}`"><td>{{ item.user }}</td><td>{{ item.host }}</td><td>{{ item.plugin }}</td><td><button class="icon-button danger" title="删除用户" @click="removeUser(item)"><Trash2 :size="16" /></button></td></tr></tbody></table></div><EmptyState v-if="!loading && !users.length" message="暂无业务用户" /></div></section></div><AppModal v-if="dbModal" title="创建数据库" :busy="loading" @close="dbModal = false" @submit="createDB"><div class="form-grid one-column"><label class="field">数据库名称<input v-model="dbForm.name" pattern="[A-Za-z0-9_]+" required></label><label class="field">字符集<select v-model="dbForm.charset"><option>utf8mb4</option><option>utf8</option><option>latin1</option></select></label></div></AppModal><AppModal v-if="userModal" title="添加数据库用户" :busy="loading" @close="userModal = false" @submit="createUser"><div class="form-grid one-column"><label class="field">用户名<input v-model="userForm.user" pattern="[A-Za-z0-9_]+" required></label><label class="field">允许主机<input v-model="userForm.host" required></label><label class="field">密码<input v-model="userForm.password" type="password" minlength="12" required></label><label class="field">授权数据库<select v-model="userForm.database"><option v-for="item in databases" :key="item.name">{{ item.name }}</option></select></label><label class="field">权限<select v-model="userForm.privileges" multiple><option value="ALL">全部权限</option><option v-for="item in ['SELECT','INSERT','UPDATE','DELETE','CREATE','ALTER','INDEX']" :key="item">{{ item }}</option></select></label></div></AppModal></template>
