<script setup lang="ts">
import { onMounted, reactive, ref } from "vue"; import { Minus, Plus, Save } from "@lucide/vue"; import { api } from "../api"; import { errorMessage, useUI } from "../ui"; import PageHeader from "../components/PageHeader.vue";
interface Extension { name: string; package: string; installed: boolean } const { notify } = useUI(); const loading = ref(false); const installed = ref(false); const version = ref(""); const extensions = ref<Extension[]>([]); const form = reactive({ uploadMaxFilesize: "64m", postMaxSize: "64m", memoryLimit: "256m", maxExecutionTime: 30, displayErrors: false });
async function load() { loading.value = true; try { const data = await api<{ installed: boolean; version: string; settings: Partial<typeof form>; extensions: Extension[] }>("/api/admin/php"); installed.value = data.installed; version.value = data.version; Object.assign(form, data.settings || {}); extensions.value = data.extensions; } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function save() { loading.value = true; try { await api("/api/admin/php/settings", { method: "PUT", body: form }); notify("PHP 设置已保存，FPM 已重启"); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function extension(item: Extension) { loading.value = true; try { await api(`/api/admin/php/extensions/${encodeURIComponent(item.name)}/${item.installed ? 'remove' : 'install'}`, { method: "POST" }); notify(`扩展 ${item.name} 已${item.installed ? '卸载' : '安装'}`); await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
onMounted(load);
</script>
<template><PageHeader title="PHP" :subtitle="version || 'PHP-FPM 设置与扩展'" kicker="RUNTIME" /><form class="settings-panel" @submit.prevent="save"><div class="section-title"><div><h2>PHP 设置</h2><span>{{ installed ? '保存后自动重启 PHP-FPM' : '请先在概览安装 PHP' }}</span></div><button class="button primary" :disabled="loading || !installed"><Save :size="16" />保存并重启</button></div><div class="form-grid"><label class="field">上传上限<input v-model="form.uploadMaxFilesize" required></label><label class="field">POST 上限<input v-model="form.postMaxSize" required></label><label class="field">内存限制<input v-model="form.memoryLimit" required></label><label class="field">执行时间（秒）<input v-model.number="form.maxExecutionTime" type="number" min="0" max="3600" required></label><label class="check-field full"><input v-model="form.displayErrors" type="checkbox">显示 PHP 错误</label></div></form><section class="section-block"><div class="section-title"><div><h2>PHP 扩展</h2><span>扩展变更后自动重启 FPM</span></div></div><div class="extension-grid"><div v-for="item in extensions" :key="item.name" class="extension-item"><div><strong>{{ item.name }}</strong><small>{{ item.package }}</small></div><button class="icon-button" :title="item.installed ? '卸载' : '安装'" :disabled="loading || !installed" @click="extension(item)"><Minus v-if="item.installed" :size="16" /><Plus v-else :size="16" /></button></div></div></section></template>
