<script setup lang="ts">
import { onMounted, reactive, ref } from "vue"; import { Plus, Save, Trash2 } from "@lucide/vue"; import { api } from "../api"; import { errorMessage, formatBytes, useUI } from "../ui"; import AppModal from "../components/AppModal.vue"; import EmptyState from "../components/EmptyState.vue"; import PageHeader from "../components/PageHeader.vue";
interface Swap { path: string; type: string; sizeBytes: number; usedBytes: number; priority: number; managed: boolean; active: boolean } interface Settings { hostname: string; timezone: string; timezones: string[]; currentTime: string; operatingSystem: string; kernel: string; architecture: string; ntpRunning: boolean; swaps: Swap[]; swapTotalBytes: number; swapUsedBytes: number }
const { notify, confirm } = useUI(); const loading = ref(false); const data = ref<Settings | null>(null); const form = reactive({ hostname: "", timezone: "" }); const swapModal = ref(false); const swapSize = ref(2048);
async function load() { loading.value = true; try { data.value = await api<Settings>("/api/admin/server-settings"); form.hostname = data.value.hostname; form.timezone = data.value.timezone; } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function save() { loading.value = true; try { await api("/api/admin/server-settings", { method: "PUT", body: form }); notify("服务器设置已保存"); await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function createSwap() { loading.value = true; try { await api("/api/admin/server-settings/swap", { method: "POST", body: { sizeMb: swapSize.value } }); notify("交换空间已创建"); swapModal.value = false; await load(); } catch (e) { notify(errorMessage(e), "error"); } finally { loading.value = false; } }
async function removeSwap() { if (!await confirm("移除 HostDesk 交换空间", "交换文件将被停用并删除；若当前内存不足，系统会拒绝操作。", "移除", true)) return; try { await api("/api/admin/server-settings/swap", { method: "DELETE" }); notify("交换空间已移除"); await load(); } catch (e) { notify(errorMessage(e), "error"); } }
onMounted(load);
</script>
<template><PageHeader title="服务器设置" subtitle="主机、时区与交换空间" kicker="SYSTEM SETTINGS" /><template v-if="data"><form class="settings-panel" @submit.prevent="save"><div class="section-title"><div><h2>基础设置</h2><span>主机标识与系统时区</span></div><button class="button primary" :disabled="loading"><Save :size="16" />保存</button></div><div class="detail-grid system-details"><div><span>操作系统</span><strong>{{ data.operatingSystem }}</strong></div><div><span>内核 / 架构</span><strong>{{ data.kernel }} · {{ data.architecture }}</strong></div><div><span>当前时间</span><strong>{{ data.currentTime.replace('T', ' ') }}</strong></div><div><span>时间同步</span><strong>{{ data.ntpRunning ? '运行中' : '未运行' }}</strong></div></div><div class="form-grid"><label class="field">服务器主机名<input v-model="form.hostname" required></label><label class="field">系统时区<select v-model="form.timezone"><option v-for="zone in data.timezones" :key="zone">{{ zone }}</option></select></label></div></form><section class="section-block"><div class="section-title"><div><h2>交换空间</h2><span>{{ formatBytes(data.swapTotalBytes) }} 总计 · {{ formatBytes(data.swapUsedBytes) }} 已用</span></div><button class="button primary" :disabled="data.swaps.some(item => item.managed)" @click="swapModal = true"><Plus :size="16" />增加交换空间</button></div><div class="data-surface"><div class="table-scroll"><table class="data-table"><thead><tr><th>设备 / 文件</th><th>类型</th><th>容量</th><th>已使用</th><th>优先级</th><th>管理方式</th><th></th></tr></thead><tbody><tr v-for="item in data.swaps" :key="item.path"><td><code>{{ item.path }}</code></td><td>{{ item.type === 'file' ? '交换文件' : '交换分区' }}</td><td>{{ formatBytes(item.sizeBytes) }}</td><td>{{ item.active ? formatBytes(item.usedBytes) : '未启用' }}</td><td>{{ item.active ? item.priority : '-' }}</td><td>{{ item.managed ? 'HostDesk' : '系统配置' }}</td><td><button v-if="item.managed" class="icon-button danger" title="移除" @click="removeSwap"><Trash2 :size="16" /></button></td></tr></tbody></table></div><EmptyState v-if="!data.swaps.length" message="当前没有交换空间" /></div></section></template><AppModal v-if="swapModal" title="增加交换空间" :busy="loading" submit-label="创建" @close="swapModal = false" @submit="createSwap"><label class="field">容量（MB）<input v-model.number="swapSize" type="number" min="256" max="131072" step="256" required></label></AppModal></template>
