<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from "vue"; import { Eraser, KeyRound, Plug, Unplug } from "@lucide/vue"; import { useUI } from "../ui"; import PageHeader from "../components/PageHeader.vue";
declare global { interface Window { Terminal: new (options: Record<string, unknown>) => any; FitAddon: { FitAddon: new () => any } } }
const { notify } = useUI(); const container = ref<HTMLElement>(); const keyInput = ref<HTMLInputElement>(); const connected = ref(false); const status = ref("未连接"); const form = reactive({ host: "127.0.0.1", port: 22, username: "", password: "", privateKey: "" }); let terminal: any; let fit: any; let socket: WebSocket | null = null; let observer: ResizeObserver | null = null;
function resize() { if (!container.value || !fit) return; requestAnimationFrame(() => { try { fit.fit(); } catch {} }); }
function init() { if (terminal || !container.value) return; if (!window.Terminal || !window.FitAddon) return notify("终端组件加载失败", "error"); terminal = new window.Terminal({ cursorBlink: true, fontFamily: '"SFMono-Regular", Consolas, monospace', fontSize: 13, lineHeight: 1.25, scrollback: 5000, theme: { background: "#151918", foreground: "#d9e1de", cursor: "#49c99a", green: "#49c99a", red: "#ef7777" } }); fit = new window.FitAddon.FitAddon(); terminal.loadAddon(fit); terminal.open(container.value); terminal.writeln("\x1b[38;5;72mHostDesk WebSSH\x1b[0m\r\n\x1b[38;5;245m等待连接...\x1b[0m"); terminal.onData((data: string) => { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: "input", data })); }); terminal.onResize(({ cols, rows }: { cols: number; rows: number }) => { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: "resize", cols, rows })); }); observer = new ResizeObserver(resize); observer.observe(container.value); resize(); }
function connect() { init(); socket?.close(); const protocol = location.protocol === "https:" ? "wss" : "ws"; socket = new WebSocket(`${protocol}://${location.host}/ws/ssh`); terminal.clear(); terminal.writeln("\x1b[38;5;245m正在建立 SSH 连接...\x1b[0m"); status.value = "连接中"; socket.onopen = () => socket?.send(JSON.stringify({ type: "connect", ...form })); socket.onmessage = ({ data }) => { const message = JSON.parse(data); if (message.type === "data") terminal.write(message.data); if (message.type === "ready") { connected.value = true; status.value = "已连接"; resize(); terminal.focus(); } if (message.type === "error") { terminal.writeln(`\r\n\x1b[31m${message.message}\x1b[0m`); connected.value = false; status.value = "连接失败"; } if (message.type === "close") disconnect(false); }; socket.onerror = () => { terminal.writeln("\r\n\x1b[31mWebSocket 连接失败\x1b[0m"); status.value = "连接失败"; }; socket.onclose = () => { connected.value = false; if (status.value === "已连接") status.value = "连接已关闭"; }; }
function disconnect(close = true) { if (close) socket?.close(); socket = null; connected.value = false; status.value = "未连接"; }
function readKey(files: FileList | null) { const file = files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { form.privateKey = String(reader.result || ""); notify("SSH 私钥已载入"); }; reader.readAsText(file); }
onMounted(() => nextTick(init)); onBeforeUnmount(() => { socket?.close(); observer?.disconnect(); terminal?.dispose(); });
</script>
<template><PageHeader title="终端" subtitle="WebSSH 连接" kicker="TERMINAL"><span class="connection-state"><i :class="{ connected }"></i>{{ status }}</span></PageHeader><form class="connection-bar" @submit.prevent="connect"><label class="field"><span>主机</span><input v-model="form.host" required></label><label class="field port"><span>端口</span><input v-model.number="form.port" type="number" min="1" max="65535" required></label><label class="field"><span>用户</span><input v-model="form.username" required autocomplete="username"></label><label class="field"><span>密码</span><input v-model="form.password" type="password" autocomplete="current-password"></label><button class="button" type="button" @click="keyInput?.click()"><KeyRound :size="16" />私钥</button><input ref="keyInput" hidden type="file" @change="readKey(($event.target as HTMLInputElement).files)"><button v-if="!connected" class="button primary" type="submit"><Plug :size="16" />连接</button><button v-else class="button" type="button" @click="disconnect()"><Unplug :size="16" />断开</button></form><div class="terminal-shell"><div class="terminal-head"><span>{{ status }}</span><button class="icon-button dark" title="清屏" @click="terminal?.clear()"><Eraser :size="16" /></button></div><div ref="container" class="terminal"></div></div></template>
